# Generated by Django 4.0.5 on 2022-06-04 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0003_alter_alert_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_alarms', to=settings.AUTH_USER_MODEL),
        ),
    ]
